### PR TITLE
[CI] Tagging docker images with github tags

### PR DESCRIPTION
**Pull request by loboda4450**
Hello!

First of all thanks for this amazing project, hopefully this will stand out of the crowd!

While developing helm chart I faced a problem of versioning - there is only "latest" version of images even though GitHub tags exists, so I came up with an idea, that I will contribute to these pipelines.

Below you can find the proof, that it actually works! 😃
https://github.com/loboda4450/voltaserve/actions/runs/9827874691/job/27131106131#step:6:5

See you in the next PRs 😄

edit: Please remember to squash, these commit messages... 😆

### CODE REVIEW

**Comment by bouassaba** [comment]
This is an awesome PR! Thanks a lot! and see you in the next PRs ;)

**Comment by dsonck92** [comment]
@bouassaba could you tag a `v2.0.1` so we can also benefit from this version locking?

**Comment by bouassaba** [comment]
@dsonck92  and @loboda4450 I want to give you contributor write access to the repository, because you guys are active on bringing great value to Voltaserve.

Also, I'm willing to change the copyright notice to say "The Voltaserve Authors" instead of my name only, this way, when you guys contribute a source file, you can mention your name on top of the file and you are the copyright holder of the code you contribute.

One more thing regarding the license, I want to protect the work of the authors by setting the license to [MariaDB's Business Source License](https://mariadb.com/bsl-faq-mariadb/), which is used by many great open source projects like  [CockroachDB](https://www.cockroachlabs.com/) and [Hashicorp](https://www.hashicorp.com/bsl), this license grants everyone the right to do anything they want with Voltaserve, individuals or organizations alike, commercial or not, as long as they don't provide it "as a service", this way, only the "The Voltaserve Authors" who put effort on the project are having the higher say and privilege.
This protects against similar cases that happened in the past where big tech companies or OEMs misuse open source projects by offering them as a service and making money with them without benefiting the authors of the project.

@dsonck92 and @loboda4450 give me a **"Yes"** approval and I proceed with what I mentioned above, by granting you access.
This way you can also do the tagging etc, that you need for your DevOps workflows.

**Comment by loboda4450** [comment]
@bouassaba Yes,  sure thing :) Currently I have a almost working helm chart which also will be PR-ed to upstream.

**Comment by dsonck92** [comment]
@bouassaba Yes, sounds good. I really jumped on this one, so I definitely want to get it to run smoothly as a replacement for my current setup.

Yes I noticed the BSL. I have my own opinions about the BSL a bit, but I understand the motivation behind it. It does align with my personal views where I usually license my own things under a license here I get what I want. Generally:

- AGPL for when I don't want corporate to simply host but not contribute their changes
- GPL for when it's not really possible to host, but I want any user of the library to contribute anything back
- LGPL if I think the library is pretty good, but I want adoption by others
- Apache if I really don't care what is done with it

Though I've also been looking into the EUPL as suggested by a colleague at work, which was similar to AGPL but more geared towards Europe, where I'm from.

Anyways, licensing aside, whichever you feel most comfortable with applying is fine by me.

**Comment by bouassaba** [comment]
Looking at our GitHub profiles, it seems that all three of us are from Europe :) I'm from Germany.
So the EUPL is definitely something worth looking at, being a license written by the "European Union"; a super powerful government organization, it's way more than "The Free Software Foundation", I'm looking forward to study this license.

**Comment by dsonck92** [comment]
Hah, I didn't even realize, your response hours made it seem different, although I'm not one to speak for burning the midnight oil on debugging what I was doing wrong trying to run this project.

Yes, I think it could be nice, and perhaps even your local government wants to adopt it at some point, seeing as local governments are more and more leaning towards open standards and less US dependence. I think this would be an interesting development. (for instance, the local tax agency decided to adopt their own Mastodon install for their "social media" Q&A)

**Pull request merged**
