### PR TITLE
Feature: enable auto fixable linters

### PR DESCRIPTION
**Pull request by dsonck92**
This MR will enable linters and apply their suggested changes. Any linters that need manual decisions are for now excluded.

### CODE REVIEW

**Comment by loboda4450** [comment]
Hello @dsonck92,

honestly I do not think that including linting within the same pipelines is a good idea. Imo it should be splitted into separate CIs.

**Comment by dsonck92** [comment]
@loboda4450 I don't quite follow. Each module has a separate pipeline. Or do you mean you want to have the linting only on MRs and excluding them on others? I'm currently not entirely up to date with the naming in Github actions as I'm using Gitlab CI myself.

**Comment by loboda4450** [comment]
I allowed myself to change them on your branch, so as not to build on each PR :D

**Comment by dsonck92** [comment]
I will cherry-pick that to the fix-module-names PR as I want to correct the module names first. This makes this PR more reliable as well (there seems to be fighting linters on how to sort the imports) I hope

**Comment by dsonck92** [comment]
@loboda4450 I realized that the old pipelines were still in the `build-*` files, I think this was not intended?

**Comment by loboda4450** [comment]
@dsonck92 obviously, I was in a rush and forgot to remove them :)

**Comment by dsonck92** [comment]
@bouassaba the `godot` linter is an autofix capable linter, but it's complaining about your style of comments as they don't follow go standards. I will delay this as it's a larger change (applying documentation to everything public). Also as note to self.

**Comment by bouassaba** [comment]
> @bouassaba the `godot` linter is an autofix capable linter, but it's complaining about your style of comments as they don't follow go standards. I will delay this as it's a larger change (applying documentation to everything public). Also as note to self.

Is it complaining about the [Swag](https://github.com/swaggo/swag) comments used to generate OpenAPI specs?

**Comment by dsonck92** [comment]
Ahhhhh, that's where they are coming from. Yeah, I think it would have been nice if that project used the `go:` prefix convention here

**Comment by bouassaba** [comment]
> Ahhhhh, that's where they are coming from. Yeah, I think it would have been nice if that project used the `go:` prefix convention here.
> 
> Well, in particular it just wants a dot at the end of a comment sentence

What if we try to add the dot and do the adjustments required by the linter, then see if the Swag generation is still working? For generating the OpenAPI with redocly, I have it documented on the README.md of each service that has it.

**Comment by dsonck92** [comment]
A convention I used in the past was to add a trailing dot at the end of the comment, which should prevent the dot from interfering with any of the instruction lines

**Comment by dsonck92** [comment]
I think these are all the automatic linters. The rest need some consideration, and especially `wsl` will completely go crazy on the formatting as it doesn't like all the compressed code. I do think, based on the code at work, that adopting it makes for pretty readable code. But sometimes it's a bit tricky to understand and definitely opinionated.

**Comment by bouassaba** [comment]
I'm all in for code readability - totally agree 👍 I will be happy to follow the recommendations suggested by the tools.

**Review by bouassaba — APPROVED** [review]

**Comment by bouassaba** [comment]
I had a look through the diff, the automatic linters are doing a pretty good job.

**Comment by bouassaba** [comment]
@dsonck92 I'm done with the new Go based `webdav`, can we also add the linters for it?

**Comment by dsonck92** [comment]
@bouassaba I think this includes everything now. There are some interesting linters we should enable for webdav though.

**Review by bouassaba — APPROVED** [review]

**Pull request merged**
