### PR TITLE
chore: remove dead code of unused feature "watermark"

### PR DESCRIPTION
**Pull request by bouassaba**
Watermark is a feature that used to exist in the product, it was allowing the user to apply a watermark on PDF or image, but this feature is not really aligned with Voltaserve's vision to be the cloud storage for creative professionals, watermark is something more for "corporate" users, so the feature has been removed from the UI before even launching 2.0 but the code stayed, so this PR removes it so we don't end up mistakenly writing tests for code that's not used.

### CODE REVIEW

**Comment by bouassaba** [comment]
Oh your point is valid, creators may need that too.
It worked before by applying a diagonal watermark on every page of a PDF, or on an image of any sort.
If the person or group has only "view" permission than they will be forced to see the "watermarked" content, if they have "edit" or above, they will see the non watermarked one.

Do you think it's worth bringing back this feature?
The only thing that was annoying me technically with this is it was a Java service.

**Comment by bouassaba** [comment]
If you say it's worth it for creators, we could bring it back as a Go implementation with some solid graphics libraries.

**Comment by dsonck92** [comment]
I think it has definitely some value, but it also definitely shouldn't be Java hahahaha. Sure I'm a bit stereotypically minded when talking about Java, but I still have yet to be proven wrong about Java eating memory like it's free. So +1 for the Go idea. I haven't worked much with the `image` library here but I don't think it should be too hard to deal with. And otherwise we could potentially expore if Rust has some good imaging libraries and PDF authoring tools. I'm good with either stack.

**Comment by bouassaba** [comment]
+1 for Rust, I like that too. Both Go an Rust have great image processing libraries.
Then I think we came to a great point of conclusion here: we bring back watermark in an implementation that would "protect" the work of an artist when shared with 3rd parties.

**Comment by dsonck92** [comment]
Yes, additionally, one feature I'm currently missing (I think) is the ability to get a public URL. While I don't mind asking people to register at my installation (which I would also like to be able to disable), for some contacts I might just need to be able to give them a link they can directly use without any registration. One-off clients would benefit from this as otherwise I burden them with more account management, and me keeping track of clients I'll never see again.

**Comment by dsonck92** [comment]
I already took the liberty, and some extensions once that is done

**Pull request merged**
